CREATE DATABASE BD_IPHARMA;
USE BD_IPHARMA;

CREATE TABLE TBL_MEDICAMENTOS (
COD_MED INT NOT NULL,
PRECO FLOAT NOT NULL,
DES VARCHAR(50) NOT NULL,
PRIMARY KEY (COD_MED)
);

CREATE TABLE TBL_LABORATORIO (
COD_LAB INT NOT NULL,
PRIMARY KEY (COD_LAB)
);

CREATE TABLE TBL_NOTA_FISCAL (
NF INT NOT NULL,
TOTAL FLOAT NOT NULL,
FP INT NOT NULL,
PRIMARY KEY (NF)
);

CREATE TABLE TBL_DROGARIA (
COD_DROGARIA INT NOT NULL,
PRIMARY KEY (COD_DROGARIA)
);

CREATE TABLE TBL_PRODUTOS (
COD_MED INT NOT NULL,
PRIMARY KEY (COD_MED),
CONSTRAINT FK_COD_MED FOREIGN KEY (COD_MED) REFERENCES TBL_MEDICAMENTOS (COD_MED)
);

CREATE TABLE TBL_ITENS_NOTA (
VALOR_TOTAL FLOAT NOT NULL,
QUANTIDADE INT NOT NULL,
PRIMARY KEY (VALOR_TOTAL)
);

-- VISUALIZAÇÃO
SELECT * FROM TBL_MEDICAMENTOS;
SELECT * FROM TBL_LABORATORIO;
SELECT * FROM TBL_NOTA_FISCAL;
SELECT * FROM TBL_DROGARIA;
SELECT * FROM TBL_PRODUTOS;
SELECT * FROM TBL_ITENS_NOTA;


CREATE PROCEDURE SP_MEDI()

SELECT COD_MED, PRECO,DES FROM MEDICAMENTOS;

CALL SP_MEDI;                     


CREATE PROCEDURE SP_LAB()

SELECT COD_LAB FROM LABORATORIO;

CALL SP_LAB;

CREATE PROCEDURE SP_NF()

SELECT NF,TOTAL,FP FROM NOTA_FISCAL;

CALL SP_NF;                         

CREATE PROCEDURE SP_DROGA()

SELECT CD_DROGA FROM DROGARIA;

CALL SP_DROGA;

CREATE PROCEDURE SP_PRODU()

SELECT CD_MED FROM PRODUTOS;

CALL SP_PRODU;

CREATE PROCEDURE SP_ITENS()

SELECT VALOR TOTAL,QUANTIDADE FROM ITENS_NOTA;

CALL SP_ITENS;


-- Triggers

SELECT * FROM TBL_MEDICAMENTOS;

SELECT * FROM TBL_LABORATORIO;

SELECT * FROM TBL_NOTA_FISCAL;

SELECT * FROM TBL_DROGARIA;

SELECT * FROM TBL_PRODUTOS;

SELECT * FROM TBL_ITENS_NOTA;

DELIMITER $$
CREATE TRIGGER TGR_VENDA_MEDICAMENTOS before INSERT ON TBL_MEDICAMENTOS
FOR EACH ROW
BEGIN
SET NEW.preco = NEW.qtde * (SELECT preco FROM des WHERE cod_med = NEW .cod_med);
END $$
DELIMITER ;
SELECT * FROM TBL_MEDICAMENTOS;
