/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thalita
 */
public class Lab extends javax.swing.JFrame {

    /**
     * Creates new form Lab
     */
    public Lab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLFixo7 = new javax.swing.JLabel();
        txtcomplm = new javax.swing.JTextField();
        btncadastro = new javax.swing.JButton();
        JLFixo2 = new javax.swing.JLabel();
        JLFixo8 = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        JLFixo9 = new javax.swing.JLabel();
        JLFixo4 = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JTextField();
        JLFixo10 = new javax.swing.JLabel();
        JLFixo5 = new javax.swing.JLabel();
        txtinsc = new javax.swing.JTextField();
        txtcep = new javax.swing.JTextField();
        JLFixo6 = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        JLFixo3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCad = new javax.swing.JTable();
        btnexcluir = new javax.swing.JButton();
        JLFixo12 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de laboratório");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JLFixo7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo7.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo7.setText("Complemento:");

        txtcomplm.setBackground(new java.awt.Color(102, 102, 102));
        txtcomplm.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtcomplm.setForeground(new java.awt.Color(255, 255, 255));
        txtcomplm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomplmActionPerformed(evt);
            }
        });

        btncadastro.setBackground(new java.awt.Color(38, 165, 182));
        btncadastro.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        btncadastro.setForeground(new java.awt.Color(255, 255, 255));
        btncadastro.setText("Cadastrar");
        btncadastro.setBorderPainted(false);
        btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroActionPerformed(evt);
            }
        });

        JLFixo2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo2.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo2.setText("Nome:");

        JLFixo8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo8.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo8.setText("Número:");

        btnvoltar.setBackground(new java.awt.Color(38, 165, 182));
        btnvoltar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        btnvoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnvoltar.setText("Voltar");
        btnvoltar.setBorderPainted(false);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        txtnome.setBackground(new java.awt.Color(102, 102, 102));
        txtnome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtnome.setForeground(new java.awt.Color(255, 255, 255));
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        txtnum.setBackground(new java.awt.Color(102, 102, 102));
        txtnum.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtnum.setForeground(new java.awt.Color(255, 255, 255));
        txtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumActionPerformed(evt);
            }
        });

        JLFixo9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo9.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo9.setText("CEP:");

        JLFixo4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo4.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo4.setText("CNPJ:");

        txtcidade.setBackground(new java.awt.Color(102, 102, 102));
        txtcidade.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtcidade.setForeground(new java.awt.Color(255, 255, 255));
        txtcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidadeActionPerformed(evt);
            }
        });

        txtcnpj.setBackground(new java.awt.Color(102, 102, 102));
        txtcnpj.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtcnpj.setForeground(new java.awt.Color(255, 255, 255));
        txtcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnpjActionPerformed(evt);
            }
        });

        JLFixo10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo10.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo10.setText("Cidade:");

        JLFixo5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo5.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo5.setText("Inscrição Estadual:");

        txtinsc.setBackground(new java.awt.Color(102, 102, 102));
        txtinsc.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtinsc.setForeground(new java.awt.Color(255, 255, 255));
        txtinsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinscActionPerformed(evt);
            }
        });

        txtcep.setBackground(new java.awt.Color(102, 102, 102));
        txtcep.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtcep.setForeground(new java.awt.Color(255, 255, 255));
        txtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcepActionPerformed(evt);
            }
        });

        JLFixo6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo6.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo6.setText("Bairro:");

        txtbairro.setBackground(new java.awt.Color(102, 102, 102));
        txtbairro.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtbairro.setForeground(new java.awt.Color(255, 255, 255));
        txtbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbairroActionPerformed(evt);
            }
        });

        JLFixo3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        JLFixo3.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo3.setText("CADASTRO DE LABORATÓRIOS");
        JLFixo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTCad.setBackground(new java.awt.Color(255, 255, 255));
        jTCad.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jTCad.setForeground(new java.awt.Color(102, 102, 102));
        jTCad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CNPJ", "Inscrição", "Bairro", "Número", "Complemento", "CEP", "Cidade", "Estado"
            }
        ));
        jTCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCadMouseClicked(evt);
            }
        });
        jTCad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCadKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTCad);

        btnexcluir.setBackground(new java.awt.Color(38, 165, 182));
        btnexcluir.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        btnexcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnexcluir.setText("Excluir");
        btnexcluir.setBorderPainted(false);
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        JLFixo12.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo12.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo12.setText("Estado:");

        txtestado.setBackground(new java.awt.Color(102, 102, 102));
        txtestado.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtestado.setForeground(new java.awt.Color(255, 255, 255));
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        jLabel1.setText("icon");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JLFixo3)
                        .addGap(380, 380, 380))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcomplm))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtinsc, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtnome))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JLFixo9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtcep))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JLFixo6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JLFixo8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtnum, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JLFixo10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtcidade))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JLFixo12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtestado)))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btncadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLFixo3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo4)
                    .addComponent(txtcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLFixo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtnum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLFixo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtinsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLFixo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLFixo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcomplm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo10)
                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastro)
                    .addComponent(btnexcluir)
                    .addComponent(btnvoltar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcomplmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomplmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomplmActionPerformed

    private void btncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroActionPerformed
        
        DefaultTableModel dtmcad = (DefaultTableModel) jTCad.getModel();
        Object[] dados = {txtnome.getText(), txtcnpj.getText(), txtinsc.getText(), txtbairro.getText(),
            txtnum.getText(), txtcomplm.getText(), txtcep.getText(), txtcidade.getText(), txtestado.getText()};
        dtmcad.addRow(dados);
    }//GEN-LAST:event_btncadastroActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal h = new TelaPrincipal();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumActionPerformed

    private void txtcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidadeActionPerformed

    private void txtcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnpjActionPerformed

    private void txtinscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinscActionPerformed

    private void txtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcepActionPerformed

    private void txtbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbairroActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        if(jTCad.getSelectedRow() != -1) {
        DefaultTableModel dtmcad = (DefaultTableModel) jTCad.getModel();
        dtmcad.removeRow(jTCad.getSelectedRow());
        }else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void jTCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCadMouseClicked
        if(jTCad.getSelectedRow() != -1) {
            txtnome.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 0).toString());
            txtcnpj.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 1).toString());
            txtinsc.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 2).toString());
            txtbairro.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 3).toString());
            txtnum.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 4).toString());
            txtcomplm.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 5).toString());
            txtcep.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 6).toString());
            txtcidade.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 7).toString());
            txtestado.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 8).toString());
        }
    }//GEN-LAST:event_jTCadMouseClicked

    private void jTCadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCadKeyReleased
        if(jTCad.getSelectedRow() != -1) {
            txtnome.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 0).toString());
            txtcnpj.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 1).toString());
            txtinsc.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 2).toString());
            txtbairro.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 3).toString());
            txtnum.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 4).toString());
            txtcomplm.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 5).toString());
            txtcep.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 6).toString());
            txtcidade.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 7).toString());
            txtestado.setText(jTCad.getValueAt(jTCad.getSelectedRow(), 8).toString());
        }
        
    }//GEN-LAST:event_jTCadKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLFixo10;
    private javax.swing.JLabel JLFixo12;
    private javax.swing.JLabel JLFixo2;
    private javax.swing.JLabel JLFixo3;
    private javax.swing.JLabel JLFixo4;
    private javax.swing.JLabel JLFixo5;
    private javax.swing.JLabel JLFixo6;
    private javax.swing.JLabel JLFixo7;
    private javax.swing.JLabel JLFixo8;
    private javax.swing.JLabel JLFixo9;
    private javax.swing.JButton btncadastro;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTCad;
    public static javax.swing.JTextField txtbairro;
    public static javax.swing.JTextField txtcep;
    public static javax.swing.JTextField txtcidade;
    public static javax.swing.JTextField txtcnpj;
    public static javax.swing.JTextField txtcomplm;
    public static javax.swing.JTextField txtestado;
    public static javax.swing.JTextField txtinsc;
    public static javax.swing.JTextField txtnome;
    public static javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
