/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thalita
 */
public class Med extends javax.swing.JFrame {

    /**
     * Creates new form Med
     */
    public Med() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCad = new javax.swing.JTable();
        btnexcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JLFixo9 = new javax.swing.JLabel();
        JLFixo4 = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JTextField();
        JLFixo5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtvalofinal = new javax.swing.JTextField();
        JLFixo6 = new javax.swing.JLabel();
        JLFixo7 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        btncadastro = new javax.swing.JButton();
        JLFixo2 = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtvalorprod = new javax.swing.JTextField();
        JLFixo3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTCad.setBackground(new java.awt.Color(255, 255, 255));
        jTCad.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jTCad.setForeground(new java.awt.Color(102, 102, 102));
        jTCad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código", "Descrição", "Quantidade", "Custo de Produção", "Valor Final"
            }
        ));
        jTCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCadMouseClicked(evt);
            }
        });
        jTCad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCadKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTCad);

        btnexcluir.setBackground(new java.awt.Color(38, 165, 182));
        btnexcluir.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        btnexcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnexcluir.setText("Excluir");
        btnexcluir.setBorderPainted(false);
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        JLFixo9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo9.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo9.setText("Valor Final:");

        JLFixo4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo4.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo4.setText("Quantidade:");

        txtquantidade.setBackground(new java.awt.Color(102, 102, 102));
        txtquantidade.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtquantidade.setForeground(new java.awt.Color(255, 255, 255));
        txtquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantidadeActionPerformed(evt);
            }
        });

        JLFixo5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo5.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo5.setText("Código:");

        txtcodigo.setBackground(new java.awt.Color(102, 102, 102));
        txtcodigo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        txtvalofinal.setBackground(new java.awt.Color(102, 102, 102));
        txtvalofinal.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtvalofinal.setForeground(new java.awt.Color(255, 255, 255));
        txtvalofinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalofinalActionPerformed(evt);
            }
        });

        JLFixo6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo6.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo6.setText("Custo de Produção:");

        JLFixo7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo7.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo7.setText("Descrição:");

        txtdesc.setBackground(new java.awt.Color(102, 102, 102));
        txtdesc.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(255, 255, 255));
        txtdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescActionPerformed(evt);
            }
        });

        btncadastro.setBackground(new java.awt.Color(38, 165, 182));
        btncadastro.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        btncadastro.setForeground(new java.awt.Color(255, 255, 255));
        btncadastro.setText("Cadastrar");
        btncadastro.setBorderPainted(false);
        btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroActionPerformed(evt);
            }
        });

        JLFixo2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        JLFixo2.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo2.setText("Nome:");

        btnvoltar.setBackground(new java.awt.Color(38, 165, 182));
        btnvoltar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        btnvoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnvoltar.setText("Voltar");
        btnvoltar.setBorderPainted(false);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        txtnome.setBackground(new java.awt.Color(102, 102, 102));
        txtnome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtnome.setForeground(new java.awt.Color(255, 255, 255));
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        txtvalorprod.setBackground(new java.awt.Color(102, 102, 102));
        txtvalorprod.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txtvalorprod.setForeground(new java.awt.Color(255, 255, 255));
        txtvalorprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorprodActionPerformed(evt);
            }
        });

        JLFixo3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        JLFixo3.setForeground(new java.awt.Color(102, 102, 102));
        JLFixo3.setText("CADASTRO DE MEDICAMENTOS");
        JLFixo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setText("icon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(JLFixo3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdesc))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(JLFixo2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnome)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtvalofinal))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtvalorprod, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLFixo4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btncadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JLFixo3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo4)
                    .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLFixo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtvalorprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLFixo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFixo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtvalofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastro)
                    .addComponent(btnexcluir)
                    .addComponent(btnvoltar))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCadMouseClicked

    }//GEN-LAST:event_jTCadMouseClicked

    private void jTCadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCadKeyReleased


    }//GEN-LAST:event_jTCadKeyReleased

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        if(jTCad.getSelectedRow() != -1) {
            DefaultTableModel dtmcad = (DefaultTableModel) jTCad.getModel();
            dtmcad.removeRow(jTCad.getSelectedRow());
        }else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void txtquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantidadeActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtvalofinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalofinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalofinalActionPerformed

    private void txtdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescActionPerformed

    private void btncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroActionPerformed

        DefaultTableModel dtmcad = (DefaultTableModel) jTCad.getModel();
        Object[] dados = {txtnome.getText(), txtcodigo.getText(), txtdesc.getText(), txtquantidade.getText(),
            txtvalorprod.getText(), txtvalofinal.getText()};
        dtmcad.addRow(dados);
        
        Estoque e = new Estoque();
        
    }//GEN-LAST:event_btncadastroActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal h = new TelaPrincipal();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtvalorprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorprodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Med().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLFixo2;
    private javax.swing.JLabel JLFixo3;
    private javax.swing.JLabel JLFixo4;
    private javax.swing.JLabel JLFixo5;
    private javax.swing.JLabel JLFixo6;
    private javax.swing.JLabel JLFixo7;
    private javax.swing.JLabel JLFixo9;
    private javax.swing.JButton btncadastro;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTCad;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdesc;
    public static javax.swing.JTextField txtnome;
    public static javax.swing.JTextField txtquantidade;
    public static javax.swing.JTextField txtvalofinal;
    public static javax.swing.JTextField txtvalorprod;
    // End of variables declaration//GEN-END:variables
}
